Repository dooingledooingle/dooingle, pull requests merged in 2024-04, with the labels that each got.

#152 refactor: 프론트엔드 UI, 레이아웃, 컨텍스트 등 리팩토링
  .github/workflows/deployment.yml
  build.gradle.kts
  dooingle-front/public/copy-button-image.svg
  dooingle-front/public/kakao_login_large_narrow.png
  dooingle-front/public/no-image-1.png
  dooingle-front/public/no-image.png
  dooingle-front/public/notice.svg
  dooingle-front/public/notification-off.svg
  dooingle-front/public/notification-on.svg
  dooingle-front/public/post-button.svg
  dooingle-front/public/report.svg
  dooingle-front/public/user-menu.svg
  dooingle-front/src/App.jsx
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/Following.jsx
  dooingle-front/src/components/FollowingUser.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/components/NoticeItem.jsx
  dooingle-front/src/components/Pagination.jsx
  dooingle-front/src/components/ProfileImageFrame.jsx
  dooingle-front/src/components/button/MorePostButton.jsx
  dooingle-front/src/components/button/SmallSubmitButton.jsx
  dooingle-front/src/components/miscellaneous/Spinner.jsx
  dooingle-front/src/components/modal/LoginInductionModal.jsx
  dooingle-front/src/components/modal/ReportModal.jsx
  dooingle-front/src/contexts/AuthContext.jsx
  dooingle-front/src/contexts/NotificationContext.jsx
  dooingle-front/src/contexts/ReportContext.jsx
  dooingle-front/src/env.js
  dooingle-front/src/fetch.js
  dooingle-front/src/hooks/useAxiosInterceptor.jsx
  dooingle-front/src/hooks/useContext.js
  dooingle-front/src/index.css
  dooingle-front/src/layouts/MainLayout.jsx
  dooingle-front/src/layouts/RootLayout.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/Follow.jsx
  dooingle-front/src/pages/Logout.jsx
  dooingle-front/src/pages/MyProfile.jsx
  dooingle-front/src/pages/Notice.jsx
  dooingle-front/src/pages/NoticeDetail.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  dooingle-front/src/pages/Welcome.jsx
  dooingle-front/tailwind.config.js
  src/main/kotlin/com/dooingle/domain/follow/dto/FollowDetailResponse.kt
  src/main/kotlin/com/dooingle/domain/notice/repository/NoticeQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/main/resources/application-dev.yml
Labels: refactor

#153 refactor: 백엔드 작업사항 일부 및 프론트엔드 UI, 레이아웃, 컨텍스트 등 리팩토링
  dooingle-front/public/copy-button-image.svg
  dooingle-front/public/kakao_login_large_narrow.png
  dooingle-front/public/no-image-1.png
  dooingle-front/public/no-image.png
  dooingle-front/public/notice.svg
  dooingle-front/public/notification-off.svg
  dooingle-front/public/notification-on.svg
  dooingle-front/public/post-button.svg
  dooingle-front/public/report.svg
  dooingle-front/public/user-menu.svg
  dooingle-front/src/App.jsx
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/Following.jsx
  dooingle-front/src/components/FollowingUser.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/components/NoticeItem.jsx
  dooingle-front/src/components/Pagination.jsx
  dooingle-front/src/components/ProfileImageFrame.jsx
  dooingle-front/src/components/button/MorePostButton.jsx
  dooingle-front/src/components/button/SmallSubmitButton.jsx
  dooingle-front/src/components/miscellaneous/Spinner.jsx
  dooingle-front/src/components/modal/LoginInductionModal.jsx
  dooingle-front/src/components/modal/ReportModal.jsx
  dooingle-front/src/contexts/AuthContext.jsx
  dooingle-front/src/contexts/NotificationContext.jsx
  dooingle-front/src/contexts/ReportContext.jsx
  dooingle-front/src/env.js
  dooingle-front/src/fetch.js
  dooingle-front/src/hooks/useAxiosInterceptor.jsx
  dooingle-front/src/hooks/useContext.js
  dooingle-front/src/index.css
  dooingle-front/src/layouts/MainLayout.jsx
  dooingle-front/src/layouts/RootLayout.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/Follow.jsx
  dooingle-front/src/pages/Logout.jsx
  dooingle-front/src/pages/MyProfile.jsx
  dooingle-front/src/pages/Notice.jsx
  dooingle-front/src/pages/NoticeDetail.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  dooingle-front/src/pages/Welcome.jsx
  dooingle-front/tailwind.config.js
  src/main/kotlin/com/dooingle/domain/follow/dto/FollowDetailResponse.kt
  src/main/kotlin/com/dooingle/domain/notice/repository/NoticeQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
Labels: refactor

#154 add: 개발/운영 배포 설정 파일, 워크플로우, 스크립트 작성
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-prod.yml
  .github/workflows/frontend-deployment.yml
  .github/workflows/frontend-preview-with-localhost.yml
  appspec.yml
  build.gradle.kts
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application-prod.yml
Labels: add

#155 add: 개발/운영 배포 분리를 위한 appspec 파일 분리
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-prod.yml
  .gitignore
  appspec.yml
  scripts/startdev.sh
  scripts/startprod.sh
Labels: add

#156 add: 셸 스크립트 버전 변경사항 누락된 부분 수정
  scripts/startdev.sh
  scripts/startprod.sh
Labels: add

#158 add: 배포 워크 플로우 등 수정 시도
  .github/workflows/deployment-dev.yml
  .github/workflows/deployment-prod.yml
  .gitignore
  appspec.yml
  scripts/start.sh
  src/main/resources/application.yml
Labels: add

#147 refactor:팔로우 수 조회 수정
  src/main/kotlin/com/dooingle/domain/follow/controller/FollowController.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
  src/test/kotlin/com/dooingle/domain/follow/service/FollowServiceDBTest.kt
Labels: refactor

#143 Test/catch
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
Labels: test

#140 Feat: SseEmitter 개수 제한
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
Labels: feat

#171 refactor: 팔로우 컨트롤러, 개인 뒹글 페이지 캐치 리스폰스 관련 리팩토링
  src/main/kotlin/com/dooingle/domain/catchdomain/dto/CatchResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/follow/controller/FollowController.kt
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceDBTest.kt
Labels: refactor

#165 add: 백엔드 개발 서버 설정 및 프론트엔드 배포 워크플로우 수정
  .github/workflows/frontend-deployment.yml
  .github/workflows/frontend-preview-with-localhost.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: add

#174 fix: notification response 관련 버그 수정
  src/main/kotlin/com/dooingle/domain/catchdomain/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/notification/dto/NotificationResponse.kt
  src/main/kotlin/com/dooingle/domain/notification/dto/NotificationSseResponse.kt
  src/main/kotlin/com/dooingle/domain/notification/model/Notification.kt
  src/main/kotlin/com/dooingle/domain/notification/repository/NotificationQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
Labels: fix

#179 fix: 테스트 환경에서 embedded redis 설정
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisClientConfig.kt
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisServerConfig.kt
  src/main/kotlin/com/dooingle/global/redis/RedisConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/follow/service/FollowServiceDBTest.kt
  src/test/kotlin/com/dooingle/global/aop/DistributedLockTest.kt
  src/test/resources/application-test.yml
Labels: fix

#157 Test: 공지사항 등록
  src/main/kotlin/com/dooingle/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/dooingle/domain/notice/service/NoticeService.kt
  src/test/kotlin/com/dooingle/domain/notice/service/NoticeServiceDBTest.kt
Labels: test

#182 Feat: 중복 신고 방지, 신고 누적 시 자동 차단
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportRepository.kt
  src/main/kotlin/com/dooingle/domain/badreport/service/BadReportService.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/dto/CatchResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleAndCatchResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleFeedResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
Labels: feat

#175 Feat: 랜덤 뒹글러 추천
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/DooinglerWithProfileResponse.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
Labels: feat

#163 test:notice 테스트코드 작성
  src/test/kotlin/com/dooingle/domain/notice/service/NoticeServiceDBTest.kt
Labels: test

#183 fix: 트랜잭션이 종료된 후 락을 해제하는 구조로 변경
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/badreport/service/BadReportService.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/global/aop/DistributedLock.kt
  src/main/kotlin/com/dooingle/global/aop/TransactionForTrailingLambda.kt
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/global/aop/DistributedLockTest.kt
Labels: fix

#144 Feat: 뜨거운 뒹글러 기능 캐시 적용
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountRedisRepository.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountService.kt
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisClientConfig.kt
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisServerConfig.kt
  src/main/kotlin/com/dooingle/global/redis/RedisConfig.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountServiceUnitTest.kt
  src/test/resources/application-test.yml
Labels: feat

#178 feat: 동시성 제어를 위한 분산락 적용
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/badreport/service/BadReportService.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/global/aop/DistributedLock.kt
  src/main/kotlin/com/dooingle/global/aop/TransactionForTrailingLambda.kt
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisClientConfig.kt
  src/main/kotlin/com/dooingle/global/redis/EmbeddedRedisServerConfig.kt
  src/main/kotlin/com/dooingle/global/redis/RedisConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/catchdomain/service/CatchServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/follow/service/FollowServiceDBTest.kt
  src/test/kotlin/com/dooingle/global/aop/DistributedLockTest.kt
  src/test/resources/application-test.yml
Labels: feat

#185 feat: 헬스 체크, 로그아웃 API
  src/main/kotlin/com/dooingle/domain/user/controller/LogoutController.kt
  src/main/kotlin/com/dooingle/global/health/HealthCheckController.kt
Labels: feat

#176 Feat/frontend/missing features
  dooingle-front/public/delete-icon.svg
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/components/modal/DeleteModal.jsx
  dooingle-front/src/fetch.js
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  dooingle-front/src/pages/Welcome.jsx
Labels: feat

#187 add: 모니터링 메트릭 중 시스템 메모리 메트릭 추가
  src/main/kotlin/com/dooingle/global/monitoring/SystemMemoryMetrics.kt
Labels: add

#188 refactor: 프론트엔드 UI 개선 dev 브랜치 반영
  dooingle-front/index.html
  dooingle-front/public/delete-icon.svg
  dooingle-front/public/dooingle-outline.svg
  dooingle-front/public/favicon.ico
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/components/modal/DeleteModal.jsx
  dooingle-front/src/fetch.js
  dooingle-front/src/index.css
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  dooingle-front/src/pages/Welcome.jsx
Labels: refactor

#194 feat: 뒹글 페이지 탐색 페이지(뒹글 페이지 검색, 랜덤 추천) 추가
  dooingle-front/public/search-icon.svg
  dooingle-front/src/App.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/FollowingUser.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/components/SearchedUser.jsx
  dooingle-front/src/components/modal/LoginInductionModal.jsx
  dooingle-front/src/fetch.js
  dooingle-front/src/layouts/MainLayout.jsx
  dooingle-front/src/pages/DooinglPagesExploration.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
Labels: feat
