Repository dooingledooingle/dooingle, pull requests merged in 2024-02, with the labels that each got.

#9 fix: Follow 엔티티의 프로퍼티에 붙은 어노테이션 수정
  src/main/kotlin/com/dooingle/domain/follow/model/Follow.kt
Labels: fix

#14 add: 프로젝트 환경 설정 수정 및 이슈 양식 수정
  .github/ISSUE_TEMPLATE/기능-추가-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/기타-추가-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/리팩토링-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/문서-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-수정-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/테스트-등록-이슈-템플릿.md
  build.gradle.kts
  src/main/kotlin/com/dooingle/global/swagger/SwaggerConfig.kt
  src/main/resources/application-local.yml
  src/main/resources/application.properties
Labels: docs, add

#12 feat: 프론트엔드 프로젝트 시작
  dooingle-front/.eslintrc.cjs
  dooingle-front/.gitignore
  dooingle-front/FRONT-README.md
  dooingle-front/index.html
  dooingle-front/package-lock.json
  dooingle-front/package.json
  dooingle-front/public/.gitkeep
  dooingle-front/src/App.jsx
  dooingle-front/src/assets/.gitkeep
  dooingle-front/src/main.jsx
  dooingle-front/src/pages/AdminHome.jsx
  dooingle-front/src/pages/Home.jsx
  dooingle-front/vite.config.js
Labels: docs, feat

#18 feat: 뜨거운 뒹글러 목록 조회 기능
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/model/DooingleCount.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountRepository.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/DooinglerResponse.kt
  src/main/kotlin/com/dooingle/domain/user/service/UserService.kt
  src/main/kotlin/com/dooingle/global/aop/StopWatch.kt
  src/main/kotlin/com/dooingle/global/aop/StopWatchAspect.kt
  src/main/kotlin/com/dooingle/global/querydsl/QueryDslConfig.kt
  src/main/kotlin/com/dooingle/global/scheduling/SchedulingConfig.kt
Labels: feat

#17 add: integration workflow 추가
  .github/workflows/integration.yml
Labels: add
