Repository dooingledooingle/dooingle, pull requests merged in 2024-03, with the labels that each got.

#30 Feat: 공지사항 등록
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/notice/controller/NoticeController.kt
  src/main/kotlin/com/dooingle/domain/notice/dto/AddNoticeRequest.kt
  src/main/kotlin/com/dooingle/domain/notice/repository/NoticeRepository.kt
  src/main/kotlin/com/dooingle/domain/notice/service/NoticeService.kt
Labels: feat

#36 Add: Security Configuration
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
Labels: add

#33 add: 액추에이터, 프로메테우스 추가 및 그라파나 동작 확인
  build.gradle.kts
  src/main/resources/application-local-h2.yml
  src/main/resources/application-local-memory-h2.yml
Labels: add

#38 Feat:follow 기능 추가
  src/main/kotlin/com/dooingle/domain/catch/dto/AddCatchRequest.kt
  src/main/kotlin/com/dooingle/domain/catch/dto/CatchResponse.kt
  src/main/kotlin/com/dooingle/domain/catch/model/Catch.kt
  src/main/kotlin/com/dooingle/domain/catch/repository/CatchRepository.kt
  src/main/kotlin/com/dooingle/domain/catch/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleController.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleQueryResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/controller/FollowController.kt
  src/main/kotlin/com/dooingle/domain/follow/dto/FollowResponse.kt
  src/main/kotlin/com/dooingle/domain/follow/model/Follow.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
  src/main/resources/application-local-memory-h2.yml
Labels: feat

#41 feat: 웰컴 페이지, 피드 페이지 화면 추가
  dooingle-front/index.html
  dooingle-front/package-lock.json
  dooingle-front/package.json
  dooingle-front/postcss.config.js
  dooingle-front/src/App.jsx
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/index.css
  dooingle-front/src/main.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/Following.jsx
  dooingle-front/src/pages/Home.jsx
  dooingle-front/src/pages/UserDooingle.jsx
  dooingle-front/src/pages/Welcome.jsx
  dooingle-front/tailwind.config.js
Labels: feat

#39 Feat: 카카오 로그인 및 회원가입
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/dooingle/dto/AddDooingleRequest.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/model/Dooingle.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleRepository.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/model/DooingleCount.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/follow/dto/FollowResponse.kt
  src/main/kotlin/com/dooingle/domain/follow/model/Follow.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
  src/main/kotlin/com/dooingle/domain/notice/dto/AddNoticeRequest.kt
  src/main/kotlin/com/dooingle/domain/notice/model/Notice.kt
  src/main/kotlin/com/dooingle/domain/notice/service/NoticeService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/OAuth2LoginController.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/DooinglerResponse.kt
  src/main/kotlin/com/dooingle/domain/user/dto/OAuth2UserInfo.kt
  src/main/kotlin/com/dooingle/domain/user/model/Profile.kt
  src/main/kotlin/com/dooingle/domain/user/model/SocialUser.kt
  src/main/kotlin/com/dooingle/domain/user/model/User.kt
  src/main/kotlin/com/dooingle/domain/user/repository/ProfileRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/dooingle/domain/user/service/OAuth2LoginService.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/domain/user/service/UserService.kt
  src/main/kotlin/com/dooingle/global/jwt/JwtHelper.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/OAuth2Client.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/OAuth2ClientService.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/KakaoOAuth2Client.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/dto/KakaoUserInfoResponse.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/dto/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/dooingle/global/oauth2/provider/OAuth2Provider.kt
  src/main/kotlin/com/dooingle/global/oauth2/provider/OAuth2ProviderConverter.kt
  src/main/kotlin/com/dooingle/global/oauth2/provider/WebConfig.kt
  src/main/kotlin/com/dooingle/global/restclient/RestClientConfig.kt
  src/main/resources/application-local-h2.yml
  src/main/resources/application-local-memory-h2.yml
Labels: feat

#47 add: 환경 변수 공유 및 중요 환경 변수 감춤
  .gitignore
  src/main/resources/application-local-h2.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: add

#48 Feat: JWT 인증/인가
  src/main/kotlin/com/dooingle/global/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/dooingle/global/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/dooingle/global/jwt/JwtHelper.kt
  src/main/kotlin/com/dooingle/global/security/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/dooingle/global/security/CustomAuthenticationEntrypoint.kt
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/security/UserPrincipal.kt
  src/main/kotlin/com/dooingle/global/swagger/SwaggerConfig.kt
Labels: feat

#49 docs: WBS 구성, 요구사항 명세서 초안 작성, 간트 차트 초안 작성
  README.md
Labels: docs

#54 feat: 프로필 수정 API
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/UpdateProfileRequest.kt
  src/main/kotlin/com/dooingle/domain/user/dto/UpdateProfileResponse.kt
  src/main/kotlin/com/dooingle/domain/user/repository/ProfileRepository.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/cloud/S3Config.kt
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/swagger/MultipartJackson2HttpMessageConverter.kt
Labels: feat

#63 Feat: SSE 기본 설정
  dooingle-front/package-lock.json
  dooingle-front/package.json
  dooingle-front/src/pages/Feed.jsx
  src/main/kotlin/com/dooingle/domain/notification/model/Notification.kt
  src/main/kotlin/com/dooingle/domain/notification/model/NotificationType.kt
  src/main/kotlin/com/dooingle/global/oauth2/provider/WebConfig.kt
  src/main/kotlin/com/dooingle/global/sse/SseController.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/main/kotlin/com/dooingle/global/web/WebConfig.kt
Labels: feat

#70 Feat: 내 뒹글의 캐치에 대한 알림, 피드 새 게시글 알림
  dooingle-front/src/pages/Feed.jsx
  src/main/kotlin/com/dooingle/domain/catchdomain/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
Labels: feat

#65 test: DooingleService, DooingleCountService 단위 테스트 코드 초안
  src/main/resources/application.yml
  src/test/kotlin/com/dooingle/DooingleApplicationTests.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooinglecount/model/DooingleCountUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountServiceUnitTest.kt
  src/test/resources/application-test.yml
Labels: test

#67 feat: 신고 엔티티 초안, 신고 등록, 목록 조회 API 초안
  src/main/kotlin/com/dooingle/domain/badreport/controller/BadReportController.kt
  src/main/kotlin/com/dooingle/domain/badreport/dto/AddBadReportRequest.kt
  src/main/kotlin/com/dooingle/domain/badreport/dto/BadReportResponse.kt
  src/main/kotlin/com/dooingle/domain/badreport/model/BadReport.kt
  src/main/kotlin/com/dooingle/domain/badreport/model/ReportedTargetType.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportRepository.kt
  src/main/kotlin/com/dooingle/domain/badreport/service/BadReportService.kt
Labels: feat

#76 feat: 프로필 단건 조회 API, 프로필 수정 API
  build.gradle.kts
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/ProfileResponse.kt
  src/main/kotlin/com/dooingle/domain/user/dto/UpdateProfileDto.kt
  src/main/kotlin/com/dooingle/domain/user/model/Profile.kt
  src/main/kotlin/com/dooingle/domain/user/repository/ProfileRepository.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
Labels: feat

#80 Feat: 팔로우 피드 기능 추가, 기존 피드 메서드 리팩토링
  src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleFeedController.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
Labels: feat, refactor

#79 feat:지난 알림 조회 기능 구현
  src/main/kotlin/com/dooingle/domain/catchdomain/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/notification/controller/NotificationController.kt
  src/main/kotlin/com/dooingle/domain/notification/dto/NotificationResponse.kt
  src/main/kotlin/com/dooingle/domain/notification/dto/NotificationSseResponse.kt
  src/main/kotlin/com/dooingle/domain/notification/repository/NotificationQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/notification/repository/NotificationQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/OAuth2LoginController.kt
Labels: feat

#87 feat: 신고된 뒹글/캐치 블락처리 기능
  src/main/kotlin/com/dooingle/domain/badreport/controller/BadReportController.kt
  src/main/kotlin/com/dooingle/domain/badreport/dto/BlockBadReportDto.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/badreport/service/BadReportService.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/model/Catch.kt
  src/main/kotlin/com/dooingle/domain/dooingle/model/Dooingle.kt
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
Labels: feat

#89 refactor: 뒹글 피드 API 응답 DTO 추가 및 API 처리 로직 수정
  src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleFeedController.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleFeedResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
Labels: refactor

#95 Refactor: 캐치 도메인 인증인가 적용
  README.md
  src/main/kotlin/com/dooingle/domain/catchdomain/controller/CatchController.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/dto/AddCatchRequest.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/dto/DeleteCatchRequest.kt
  src/main/kotlin/com/dooingle/domain/catchdomain/service/CatchService.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
Labels: refactor

#96 feat: 프로필 이미지 확장자 및 용량 제한
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/resources/application.yml
  src/test/kotlin/com/dooingle/domain/user/service/SocialUserServiceTest.kt
Labels: feat

#98 docs: README.md 파일 수정
  README.md
  readme-images/architecture-2024-03-18.png
Labels: docs

#101 add: 백엔드 배포 워크플로우 작성 및 환경 변수 정리, 기타 워크플로우 정리
  .github/workflows/deployment.yml
  .github/workflows/frontend-deployment-with-dev-server.yml
  .github/workflows/frontend-preview-with-localhost.yml
  .github/workflows/integration.yml
  .gitignore
  appspec.yml
  build.gradle.kts
  dooingle-front/src/env.js
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: add

#102 Test: 팔로우 피드 조회 통합 테스트
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
Labels: test

#112 Test: 알림 기능 테스트, Refactor: 알림 기능 리팩토링
  build.gradle.kts
  dooingle-front/src/pages/Feed.jsx
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/notification/controller/NotificationController.kt
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
Labels: test

#110 refactor: CORS 설정 리팩토링 및 프론트엔드 axios 설정
  dooingle-front/src/pages/Feed.jsx
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/web/WebConfig.kt
Labels: refactor

#119 feat: 프론트엔드 뒹글 피드 페이지 기능 MVP 추가(알림 및 뒹글 링크 제외)
  dooingle-front/public/.gitkeep
  dooingle-front/public/no-image.png
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/ProfileImageFrame.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/Welcome.jsx
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
Labels: feat

#120 refactor: SocialUser 엔티티에 userLink 프로퍼티 추가 및 요청, 응답 시 userId 대신 userLink 사용
  dooingle-front/src/pages/Welcome.jsx
  src/main/kotlin/com/dooingle/domain/badreport/dto/BadReportResponse.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleController.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleAndCatchResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleFeedResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/DooinglerResponse.kt
  src/main/kotlin/com/dooingle/domain/user/model/SocialUser.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserRepository.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/exception/custom/SocialUserNotFoundByUserLinkException.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
Labels: refactor

#117 test: 프로필 조회/수정 테스트
  src/test/kotlin/com/dooingle/domain/user/service/SocialUserServiceTest.kt
Labels: test

#121 refactor: userLink 사용 누락된 곳변경
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountQueryDslRepositoryImpl.kt
Labels: refactor

#123 refactor: CORS 설정 리팩토링
  dooingle-front/src/pages/Feed.jsx
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/web/WebConfig.kt
Labels: refactor

#125 feat: 프론트엔드 개인 뒹글 페이지 구현
  dooingle-front/src/App.jsx
  dooingle-front/src/components/DooingleAndCatch.jsx
  dooingle-front/src/components/DooinglerListAside.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/components/ProfileImageFrame.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  src/main/kotlin/com/dooingle/domain/badreport/dto/BadReportResponse.kt
  src/main/kotlin/com/dooingle/domain/badreport/repository/BadReportQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/controller/DooingleController.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleAndCatchResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleFeedResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/dto/DooingleResponse.kt
  src/main/kotlin/com/dooingle/domain/dooingle/repository/DooingleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/dooingle/service/DooingleService.kt
  src/main/kotlin/com/dooingle/domain/dooinglecount/repository/DooingleCountQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/follow/controller/FollowController.kt
  src/main/kotlin/com/dooingle/domain/follow/dto/IsFollowingUserResponse.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
  src/main/kotlin/com/dooingle/domain/user/dto/DooinglerResponse.kt
  src/main/kotlin/com/dooingle/domain/user/dto/ProfileImageUrlResponse.kt
  src/main/kotlin/com/dooingle/domain/user/model/SocialUser.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/user/repository/SocialUserRepository.kt
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/exception/custom/SocialUserNotFoundByUserLinkException.kt
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/dooinglecount/service/DooingleCountServiceUnitTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
Labels: feat, refactor

#122 Test: 카카오 로그인 및 회원가입, Feat: 프로필 기본 이미지 여부 확인
  src/main/kotlin/com/dooingle/domain/user/service/SocialUserService.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/dto/KakaoUserInfoResponse.kt
  src/main/kotlin/com/dooingle/global/oauth2/client/kakao/dto/KakaoUserPropertiesResponse.kt
  src/test/kotlin/com/dooingle/domain/badreport/service/BadReportServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/dooingle/service/DooingleServiceDBTest.kt
  src/test/kotlin/com/dooingle/domain/notification/service/NotificationSseTest.kt
  src/test/kotlin/com/dooingle/domain/user/service/OAuth2LoginServiceTest.kt
  src/test/kotlin/com/dooingle/domain/user/service/SocialUserServiceDBTest.kt
  src/test/kotlin/com/dooingle/global/jwt/JwtHelperTest.kt
Labels: test

#128 feat: 프론트엔드 사용자 프로필 수정 페이지 기능
  dooingle-front/src/App.jsx
  dooingle-front/src/components/Header.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/pages/MyProfile.jsx
  src/main/kotlin/com/dooingle/domain/user/controller/UserController.kt
Labels: feat

#129 feat: 프론트엔드 팔로우 페이지 MVP 기능 구현
  dooingle-front/src/App.jsx
  dooingle-front/src/components/Following.jsx
  dooingle-front/src/components/Navigation.jsx
  dooingle-front/src/pages/Follow.jsx
  dooingle-front/src/pages/Following.jsx
  src/main/kotlin/com/dooingle/domain/follow/controller/FollowController.kt
  src/main/kotlin/com/dooingle/domain/follow/dto/FollowDetailResponse.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowQueryDslRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowQueryDslRepositoryImpl.kt
  src/main/kotlin/com/dooingle/domain/follow/repository/FollowRepository.kt
  src/main/kotlin/com/dooingle/domain/follow/service/FollowService.kt
Labels: feat, refactor

#133 feat: 프론트엔드 피드 페이지 알림 시 UI 표시, 뒹글의 답변 유무 표시, 링크 등 구현
  dooingle-front/src/components/Dooingle.jsx
  dooingle-front/src/main.jsx
  dooingle-front/src/pages/Feed.jsx
  dooingle-front/src/pages/PersonalDooingle.jsx
  src/main/kotlin/com/dooingle/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/dooingle/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/dooingle/global/security/SecurityConfig.kt
  src/main/kotlin/com/dooingle/global/sse/SseEmitters.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local-dev-infra.yml
  src/main/resources/application-local-h2.yml
  src/main/resources/application-local-memory-h2.yml
Labels: fix, feat

#137 add: AWS RDS MySQL 사용
  .github/workflows/deployment.yml
  build.gradle.kts
  src/main/resources/application-dev.yml
Labels: add
